name: Test and Lint

on:
  push:
    branches: [ main ]
  pull_request:
    # Removing the branches filter makes it run on all PRs
    
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MIN_COVERAGE: 85
      
    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: 'apps/api/package.json'

    - name: Install dependencies, setup Prisma and run tests
      working-directory: apps/api
      run: |
        npm install
        npx prisma generate
        npm test -- --coverage --coverageThreshold='{"global":{"lines":${{ env.MIN_COVERAGE }}}}'

  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install API dependencies
      working-directory: apps/api
      run: npm install

    - name: Install Web dependencies
      working-directory: apps/web
      run: npm install

    - name: Run API lint
      working-directory: apps/api
      run: npm run lint

    - name: Run Web lint
      working-directory: apps/web
      run: npm run lint